### ISSUE TITLE
Incorrect publish method in assessment notification dispatch

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/stam-acasa#230]
Currently, the assessment notification dispatch job fails with the following call stack:

```
StamAcasa.JobScheduler.Jobs.SendAssessmentReminderJob[0]
stamacasa.jobscheduler_1  |       Error when dispatching assessment reminder notification: to do.
stamacasa.jobscheduler_1  | System.NotImplementedException: to do
stamacasa.jobscheduler_1  |    at StamAcasa.Common.Queue.QueueService.PublishNotification[T](T message) in /src/StamAcasa.Common/Queue/QueueService.cs:line 28
stamacasa.jobscheduler_1  |    at StamAcasa.Common.Notifications.AssessmentNotificationsDispatch.Process() in /src/StamAcasa.Common/Notifications/AssessmentNotificationsDispatch.cs:line 29
stamacasa.jobscheduler_1  |    at StamAcasa.JobScheduler.Jobs.SendAssessmentReminderJob.RunAsync(CancellationToken cancellationToken) in /src/StamAcasa.JobScheduler/Jobs/SendAssessmentReminderJob.cs:line 33
```

This is because the service uses the unimplemented PostNotification method and not the PostEmailRequest method. This needs to be changed in `AssessmentNotificationDispatch.cs` at line 27.

**Comment by irinel-nistor** [comment]
I'd like to work on this one

**Comment by RaduCStefanescu** [comment]
This is a `dotnet` issue, are you good with that?

**Comment by irinel-nistor** [comment]
yes, I'm mainly a dotnet backend developer

**Comment by RaduCStefanescu** [comment]
Great, cause you handled a lot of frontend issues these days.
It's all yours!
