### ISSUE TITLE
Scheduler service fails when sending emails for daily assessments

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/stam-acasa#339]
The scheduler service in development environment fails when sending the daily assessment emails with the following error:
```
2020-04-23 12:46:00 [INFO]<8> [StamAcasa.JobScheduler.JobScheduler] Running job StamAcasa.JobScheduler.Jobs.SendAssessmentReminderJob at 04/23/2020 12:46:00 +00:00
stamacasa.jobscheduler_1  | Unhandled exception. System.ArgumentException: An item with the same key has already been added. Key: 1_1_true
stamacasa.jobscheduler_1  |    at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
stamacasa.jobscheduler_1  |    at CallSite.Target(Closure , CallSite , Dictionary`2 , String , Object )
stamacasa.jobscheduler_1  |    at StamAcasa.Common.Services.Excel.AnswersExcelExporter.FillSingleChoiceMapFromFormString(String formNewUser) in /src/StamAcasa.Common/Services/Excel/AnswersExcelExporter.cs:line 35
stamacasa.jobscheduler_1  |    at StamAcasa.Common.Services.Excel.AnswersExcelExporter..ctor(IExcelDocumentService excelDocumentService, IAssessmentFormProvider assessmentFormProvider) in /src/StamAcasa.Common/Services/Excel/AnswersExcelExporter.cs:line 23
```

**Comment by idormenco** [comment]
will fix
