### ISSUE TITLE
DllNotFoundException on dev environment

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/stam-acasa#347]
Sending assessment results fails on dev environment with the following error:
```
stamacasa.jobscheduler_1  | 2020-04-23 18:30:00 [EROR]<8> [StamAcasa.JobScheduler.Jobs.SendResultsNotificationJob] Error when dispatching results notification: The type initializer for 'Gdip' threw an exception..
stamacasa.jobscheduler_1  | System.TypeInitializationException: The type initializer for 'Gdip' threw an exception.
stamacasa.jobscheduler_1  |  ---> System.DllNotFoundException: Unable to load shared library 'libdl' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibdl: cannot open shared object file: No such file or directory
stamacasa.jobscheduler_1  |    at Interop.Libdl.dlopen(String fileName, Int32 flag)
stamacasa.jobscheduler_1  |    at System.Drawing.SafeNativeMethods.Gdip.LoadNativeLibrary()
stamacasa.jobscheduler_1  |    at System.Drawing.SafeNativeMethods.Gdip..cctor()
stamacasa.jobscheduler_1  |    --- End of inner exception stack trace ---
stamacasa.jobscheduler_1  |    at System.Drawing.SafeNativeMethods.Gdip.GdipGetGenericFontFamilySansSerif(IntPtr& fontfamily)
stamacasa.jobscheduler_1  |    at System.Drawing.FontFamily.GetGdipGenericSansSerif()
stamacasa.jobscheduler_1  |    at System.Drawing.FontFamily.get_GenericSansSerif()
stamacasa.jobscheduler_1  |    at System.Drawing.Font.CreateFont(String familyName, Single emSize, FontStyle style, GraphicsUnit unit, Byte charSet, Boolean isVertical)
stamacasa.jobscheduler_1  |    at System.Drawing.Font..ctor(String familyName, Single emSize, FontStyle style, GraphicsUnit unit, Byte gdiCharSet, Boolean gdiVerticalFont)
stamacasa.jobscheduler_1  |    at System.Drawing.Font..ctor(String familyName, Single emSize, FontStyle style, GraphicsUnit unit)
stamacasa.jobscheduler_1  |    at NPOI.SS.Util.SheetUtil.IFont2Font(IFont font1)
stamacasa.jobscheduler_1  |    at NPOI.SS.Util.SheetUtil.GetDefaultCharWidth(IWorkbook wb)
stamacasa.jobscheduler_1  |    at NPOI.SS.Util.SheetUtil.GetColumnWidth(ISheet sheet, Int32 column, Boolean useMergedCells, Int32 firstRow, Int32 lastRow)
stamacasa.jobscheduler_1  |    at NPOI.SS.Util.SheetUtil.GetColumnWidth(ISheet sheet, Int32 column, Boolean useMergedCells)
stamacasa.jobscheduler_1  |    at NPOI.XSSF.UserModel.XSSFSheet.AutoSizeColumn(Int32 column, Boolean useMergedCells)
stamacasa.jobscheduler_1  |    at NPOI.XSSF.UserModel.XSSFSheet.AutoSizeColumn(Int32 column)
stamacasa.jobscheduler_1  |    at StamAcasa.Common.Services.Excel.ExcelDocumentService.DataTableToXlsxFile(DataTable dataTable, String sheetName) in /src/StamAcasa.Common/Services/Excel/ExcelDocumentService.cs:line 103
stamacasa.jobscheduler_1  |    at StamAcasa.Common.Services.Excel.AnswersExcelExporter.AnswersToExcel(IList`1 jAnswerForms, AnswersExcelTemplateTypes template) in /src/StamAcasa.Common/Services/Excel/AnswersExcelExporter.cs:line 59
stamacasa.jobscheduler_1  |    at StamAcasa.Common.Services.Excel.IAnswersExcelExporter.AnswersToExcel(JArray jAnswerForms, AnswersExcelTemplateTypes template) in /src/StamAcasa.Common/Services/Excel/IAnswersExcelExporter.cs:line 10
stamacasa.jobscheduler_1  |    at StamAcasa.Common.Notifications.ResultNotificationsDispatch.SendEmailsForList(IEnumerable`1 forms, ResultsNotificationEmailData emailData) in /src/StamAcasa.Common/Notifications/ResultNotificationsDispatch.cs:line 80
stamacasa.jobscheduler_1  |    at StamAcasa.Common.Notifications.ResultNotificationsDispatch.Process() in /src/StamAcasa.Common/Notifications/ResultNotificationsDispatch.cs:line 58
stamacasa.jobscheduler_1  |    at StamAcasa.JobScheduler.Jobs.SendResultsNotificationJob.RunAsync(CancellationToken cancellationToken) in /src/StamAcasa.JobScheduler/Jobs/SendResultsNotificationJob.cs:line 27
```

**Comment by idormenco** [comment]
Will fix , tomorrow

**Comment by RaduCStefanescu** [comment]
The solution is to install this in the Dockerfile for Scheduler:
```
# install System.Drawing native dependencies
RUN apt-get update \
    && apt-get install -y --allow-unauthenticated \
        libc6-dev \
        libgdiplus \
        libx11-dev \
     && rm -rf /var/lib/apt/lists/*
```
More information here: https://github.com/dotnet/dotnet-docker/issues/618
