### ISSUE TITLE
Scheduler fails in production

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/stam-acasa#411]
Scheduler fails in production after a few hours with the following error:

```
2020-05-01 01:29:59 [INFO]<13> [StamAcasa.JobScheduler.Jobs.HealthCheckJob] Job HealthCheckJob ran at 05/01/2020 01:29:59 +00:00
Unhandled exception. System.ArgumentException: '-0.0065' is not a valid value for 'Interval'. 'Interval' must be greater than 0.
   at System.Timers.Timer.set_Interval(Double value)
   at StamAcasa.JobScheduler.JobScheduler.<>c__DisplayClass6_1.<<ScheduleConfiguredJobs>b__0>d.MoveNext() in /src/StamAcasa.JobScheduler/JobScheduler.cs:line 87
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

**Comment by idormenco** [comment]
i will take this
