### ISSUE TITLE
Add simple button with link in My Profile

### ISSUE THREAD

**Issue by overeha** [code4romania/stam-acasa#480]
Add a button in My account. under the historical data box. Just like in the simulations below

The button should have
- this color #FFBD59
- this text Completează formular
- Link to your evaluation form if you are on ”Profilul meu” tab. OR link to the evaluation form for another family member.

![image](https://user-images.githubusercontent.com/45068169/87229778-c206a880-c3b3-11ea-8536-0de789612fe9.png)

![image](https://user-images.githubusercontent.com/45068169/87229827-27f33000-c3b4-11ea-85b5-7b89bcc324d8.png)

**Comment by popsorina** [comment]
I will take this one

**Comment by RaduCStefanescu** [comment]
All yours @popsorina

**Comment by popsorina** [comment]
@RaduCStefanescu I cannot start the backend, I have this error:

```
stamacasa.api_1           | Application startup exception: System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (00000005, 0xFFFDFFFF): Name or service not known
stamacasa.api_1           |    at System.Net.Dns.InternalGetHostByName(String hostName)
stamacasa.api_1           |    at System.Net.Dns.GetHostAddresses(String hostNameOrAddress)
stamacasa.api_1           |    at Npgsql.NpgsqlConnector.Connect(NpgsqlTimeout timeout)
stamacasa.api_1           |    at Npgsql.NpgsqlConnector.RawOpen(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
stamacasa.api_1           |    at Npgsql.NpgsqlConnector.Open(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
stamacasa.api_1           |    at Npgsql.NpgsqlConnection.<>c__DisplayClass32_0.<<Open>g__OpenLong|0>d.MoveNext()
stamacasa.api_1           | --- End of stack trace from previous location where exception was thrown ---
stamacasa.api_1           |    at Npgsql.NpgsqlConnection.Open()
stamacasa.api_1           |    at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlDatabaseCreator.Exists()
stamacasa.api_1           |    at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.Exists()
stamacasa.api_1           |    at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
stamacasa.api_1           |    at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.Migrate(DatabaseFacade databaseFacade)
stamacasa.api_1           |    at StamAcasa.Api.Startup.Configure(IApplicationBuilder app, UserDbContext dbContext) in /src/StamAcasa.Api/Startup.cs:line 103
stamacasa.api_1           |    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
stamacasa.api_1           |    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
stamacasa.api_1           |    at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
stamacasa.api_1           |    at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
stamacasa.api_1           |    at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
stamacasa.api_1           |    at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
stamacasa.api_1           |    at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
stamacasa.api_1           |    at Microsoft.AspNetCore.Hosting.WebHost.BuildApplication()
stamacasa.api_1           | 2020-08-17 16:43:16 [FATL]<1> [Microsoft.AspNetCore.Hosting.WebHost] Application startup exception
stamacasa.api_1           | System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (00000005, 0xFFFDFFFF): Name or service not known
stamacasa.api_1           |    at System.Net.Dns.InternalGetHostByName(String hostName)
stamacasa.api_1           |    at System.Net.Dns.GetHostAddresses(String hostNameOrAddress)
stamacasa.api_1           |    at Npgsql.NpgsqlConnector.Connect(NpgsqlTimeout timeout)
stamacasa.api_1           |    at Npgsql.NpgsqlConnector.RawOpen(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
stamacasa.api_1           |    at Npgsql.NpgsqlConnector.Open(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
stamacasa.api_1           |    at Npgsql.NpgsqlConnection.<>c__DisplayClass32_0.<<Open>g__OpenLong|0>d.MoveNext()
stamacasa.api_1           | --- End of stack trace from previous location where exception was thrown ---
stamacasa.api_1           |    at Npgsql.NpgsqlConnection.Open()
stamacasa.api_1           |    at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlDatabaseCreator.Exists()
stamacasa.api_1           |    at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.Exists()
stamacasa.api_1           |    at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
stamacasa.api_1           |    at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.Migrate(DatabaseFacade databaseFacade)
stamacasa.api_1           |    at StamAcasa.Api.Startup.Configure(IApplicationBuilder app, UserDbContext dbContext) in /src/StamAcasa.Api/Startup.cs:line 103
stamacasa.api_1           |    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
stamacasa.api_1           |    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
stamacasa.api_1           |    at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
stamacasa.api_1           |    at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
stamacasa.api_1           |    at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
stamacasa.api_1           |    at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
stamacasa.api_1           |    at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
stamacasa.api_1           |    at Microsoft.AspNetCore.Hosting.WebHost.BuildApplication()
stamacasa.api_1           | 2020-08-17 16:43:16 [FATL]<1> [] Host terminated unexpectedly
stamacasa.api_1           | System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (00000005, 0xFFFDFFFF): Name or service not known
stamacasa.api_1           |    at System.Net.Dns.InternalGetHostByName(String hostName)
stamacasa.api_1           |    at System.Net.Dns.GetHostAddresses(String hostNameOrAddress)
stamacasa.api_1           |    at Npgsql.NpgsqlConnector.Connect(NpgsqlTimeout timeout)
stamacasa.api_1           |    at Npgsql.NpgsqlConnector.RawOpen(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
stamacasa.api_1           |    at Npgsql.NpgsqlConnector.Open(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
stamacasa.api_1           |    at Npgsql.NpgsqlConnection.<>c__DisplayClass32_0.<<Open>g__OpenLong|0>d.MoveNext()
stamacasa.api_1           | --- End of stack trace from previous location where exception was thrown ---
stamacasa.api_1           |    at Npgsql.NpgsqlConnection.Open()
stamacasa.api_1           |    at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlDatabaseCreator.Exists()
stamacasa.api_1           |    at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.Exists()
stamacasa.api_1           |    at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
stamacasa.api_1           |    at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.Migrate(DatabaseFacade databaseFacade)
stamacasa.api_1           |    at StamAcasa.Api.Startup.Configure(IApplicationBuilder app, UserDbContext dbContext) in /src/StamAcasa.Api/Startup.cs:line 103
stamacasa.api_1           |    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
stamacasa.api_1           |    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
stamacasa.api_1           |    at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
stamacasa.api_1           |    at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
stamacasa.api_1           |    at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
stamacasa.api_1           |    at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
stamacasa.api_1           |    at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
stamacasa.api_1           |    at Microsoft.AspNetCore.Hosting.WebHost.BuildApplication()
stamacasa.api_1           |    at Microsoft.AspNetCore.Hosting.WebHost.StartAsync(CancellationToken cancellationToken)
stamacasa.api_1           |    at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String startupMessage)
stamacasa.api_1           |    at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String startupMessage)
stamacasa.api_1           |    at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token)
stamacasa.api_1           |    at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
stamacasa.api_1           |    at StamAcasa.Api.Program.Main(String[] args) in /src/StamAcasa.Api/Program.cs:line 39
stamacasa.api_1           | 2020-08-17 16:43:16 [INFO]<1> [] Stopped
src_stamacasa.api_1 exited with code 0
```

**Comment by RaduCStefanescu** [comment]
Hi @popsorina 
Please run the `docker-compose-dep.yml` file first, wait for the dependencies to be initialized, and then run the `docker-compose-services.yml` to start the services.
